import type { BlogItem } from "@/types";

export const MOCK_BLOGS: BlogItem[] = [
	{
		id: "1",
		title: "Railsの基本",
		content:
			"これはRailsに関するブログ記事です。APIの作成方法やReactとの連携について解説しています。",
		description:
			"これはRailsに関するブログ記事です。APIの作成方法やReactとの連携について解説しています。",
		author: "著者1",
		link: "/blogs/1/",
		thumbnail: undefined,
		published_at: "2026-01-30T07:52:45.912Z",
		tags: ["Rails", "JavaScript", "Ruby"],
	},
	{
		id: "2",
		title:
			"限界学生の就職活動体験記 ～貯金ゼロ、ES全滅、面接連敗の僕が、それでもスーツを着て今日も社会に祈りを捧げる話～",
		content: "キーワード検索・タグ検索のテスト用です。",
		description: "キーワード検索・タグ検索のテスト用です。",
		author: "著者2",
		link: "/blogs/2/",
		thumbnail: undefined,
		published_at: "2026-01-10T00:00:00.000Z",
		tags: ["就職活動", "ポエム", "IT業界", "反面教師"],
	},
	{
		id: "3",
		title: "サンプル記事",
		content: "サンプル記事です。",
		description: "サンプル記事です。",
		author: "著者3",
		link: "/blogs/3/",
		thumbnail: undefined,
		published_at: "2026-01-01T00:00:00.000Z",
		tags: ["お知らせ"],
	},
	{
		id: "4",
		title: "Reactの始め方",
		content: "Reactのインストール方法と基本的な使い方をまとめました。",
		description: "Reactのインストール方法と基本的な使い方をまとめました。",
		author: "著者4",
		link: "/blogs/4/",
		thumbnail: undefined,
		published_at: "2026-02-01T11:00:00.000Z",
		tags: ["React", "JavaScript"],
	},
	{
		id: "5",
		title: "Python基礎講座",
		content: "Pythonの文法や基本的な使い方をわかりやすく解説します。",
		description: "Pythonの文法や基本的な使い方をわかりやすく解説します。",
		author: "著者5",
		link: "/blogs/5/",
		thumbnail: undefined,
		published_at: "2026-02-03T09:00:00.000Z",
		tags: ["Python", "プログラミング"],
	},
	{
		id: "6",
		title: "就活の心得",
		content: "就職活動を乗り切るためのポイントを紹介します。",
		description: "就職活動を乗り切るためのポイントを紹介します。",
		author: "著者6",
		link: "/blogs/6/",
		thumbnail: undefined,
		published_at: "2026-02-04T10:15:00.000Z",
		tags: ["就職活動", "Tips"],
	},
	{
		id: "7",
		title: "ライフハック集",
		content: "日常を便利にするライフハックをまとめてみました。",
		description: "日常を便利にするライフハックをまとめてみました。",
		author: "著者7",
		link: "/blogs/7/",
		thumbnail: undefined,
		published_at: "2026-02-05T16:00:00.000Z",
		tags: ["ライフハック", "生活"],
	},
	{
		id: "8",
		title: "Vue.jsとReactの違い",
		content: "フロントエンドフレームワークVue.jsとReactの特徴を比較します。",
		description: "フロントエンドフレームワークVue.jsとReactの特徴を比較します。",
		author: "著者8",
		link: "/blogs/8/",
		thumbnail: undefined,
		published_at: "2026-02-06T12:30:00.000Z",
		tags: ["React", "Vue.js"],
	},
	{
		id: "9",
		title: "Docker入門",
		content: "開発効率向上のためのDocker活用法について解説します。",
		description: "開発効率向上のためのDocker活用法について解説します。",
		author: "著者9",
		link: "/blogs/9/",
		thumbnail: undefined,
		published_at: "2026-02-07T14:22:00.000Z",
		tags: ["Docker", "プログラミング"],
	},
	{
		id: "10",
		title: "学生時代にやるべきこと",
		content: "学生のうちに経験しておきたいこと5選。",
		description: "学生のうちに経験しておきたいこと5選。",
		author: "著者10",
		link: "/blogs/10/",
		thumbnail: undefined,
		published_at: "2026-02-08T10:05:00.000Z",
		tags: ["学生", "経験談"],
	},
	{
		id: "11",
		title: "JavaScriptの非同期処理",
		content: "Promiseとasync/awaitの違いや使い方を解説。",
		description: "Promiseとasync/awaitの違いや使い方を解説。",
		author: "著者11",
		link: "/blogs/11/",
		thumbnail: undefined,
		published_at: "2026-02-09T13:14:00.000Z",
		tags: ["JavaScript", "プログラミング"],
	},
	{
		id: "12",
		title: "面接必勝法",
		content: "会社面接で意識すること・よく聞かれる質問についてまとめました。",
		description: "会社面接で意識すること・よく聞かれる質問についてまとめました。",
		author: "著者12",
		link: "/blogs/12/",
		thumbnail: undefined,
		published_at: "2026-02-10T15:30:00.000Z",
		tags: ["面接", "就職活動"],
	},
	{
		id: "13",
		title: "SQL基礎",
		content: "データの取得や更新など、SQLの基本操作について説明しています。",
		description: "データの取得や更新など、SQLの基本操作について説明しています。",
		author: "著者13",
		link: "/blogs/13/",
		thumbnail: undefined,
		published_at: "2026-02-11T19:00:00.000Z",
		tags: ["SQL", "プログラミング"],
	},
	{
		id: "14",
		title: "失敗から学ぶ",
		content: "大きな失敗をした経験とそこから得た教訓を共有します。",
		description: "大きな失敗をした経験とそこから得た教訓を共有します。",
		author: "著者14",
		link: "/blogs/14/",
		thumbnail: undefined,
		published_at: "2026-02-12T20:23:00.000Z",
		tags: ["反面教師", "経験談"],
	},
	{
		id: "15",
		title: "Next.jsの特徴",
		content: "人気急上昇中のNext.jsでできること、メリットなどを紹介します。",
		description: "人気急上昇中のNext.jsでできること、メリットなどを紹介します。",
		author: "著者15",
		link: "/blogs/15/",
		thumbnail: undefined,
		published_at: "2026-02-13T10:00:00.000Z",
		tags: ["Next.js", "JavaScript"],
	},
	{
		id: "16",
		title: "ReactでTodoアプリを作る",
		content: "Reactを使ってシンプルなTodoアプリを作成する手順を紹介します。",
		description: "Reactを使ってシンプルなTodoアプリを作成する手順を紹介します。",
		author: "著者4",
		link: "/blogs/16/",
		thumbnail: undefined,
		published_at: "2026-02-14T08:30:00.000Z",
		tags: ["React", "JavaScript", "プログラミング"],
	},
	{
		id: "17",
		title: "読書記録2026年2月",
		content: "今月読んだ本の中で特におすすめの3冊を紹介。",
		description: "今月読んだ本の中で特におすすめの3冊を紹介。",
		author: "著者16",
		link: "/blogs/17/",
		thumbnail: undefined,
		published_at: "2026-02-15T13:00:00.000Z",
		tags: ["書評", "Book"],
	},
	{
		id: "18",
		title: "Web APIとは？",
		content: "Web APIの基礎知識と活用事例について解説します。",
		description: "Web APIの基礎知識と活用事例について解説します。",
		author: "著者17",
		link: "/blogs/18/",
		thumbnail: undefined,
		published_at: "2026-02-16T21:00:00.000Z",
		tags: ["API", "JavaScript"],
	},
	{
		id: "19",
		title: "効率的な勉強法",
		content: "効率よく学習を進めるためのコツや習慣を紹介します。",
		description: "効率よく学習を進めるためのコツや習慣を紹介します。",
		author: "著者5",
		link: "/blogs/19/",
		thumbnail: undefined,
		published_at: "2026-02-17T14:00:00.000Z",
		tags: ["勉強法", "Tips"],
	},
	{
		id: "20",
		title: "プログラミング初心者のつまずきポイント",
		content: "プログラミング初心者がよく直面する課題とその解決策をまとめました。",
		description: "プログラミング初心者がよく直面する課題とその解決策をまとめました。",
		author: "著者18",
		link: "/blogs/20/",
		thumbnail: undefined,
		published_at: "2026-02-18T18:00:00.000Z",
		tags: ["プログラミング", "Tips"],
	},
	{
		id: "21",
		title: "コンピュータサイエンス入門",
		content: "CSを学ぶ上で知っておきたい基礎知識をまとめました。",
		description: "CSを学ぶ上で知っておきたい基礎知識をまとめました。",
		author: "著者19",
		link: "/blogs/21/",
		thumbnail: undefined,
		published_at: "2026-02-19T12:00:00.000Z",
		tags: ["プログラミング", "CS"],
	},
	{
		id: "22",
		title: "リモートワークのコツ",
		content: "家で働く時に気をつけたいことをまとめています。",
		description: "家で働く時に気をつけたいことをまとめています。",
		author: "著者20",
		link: "/blogs/22/",
		thumbnail: undefined,
		published_at: "2026-02-20T14:00:00.000Z",
		tags: ["リモートワーク", "Tips"],
	},
	{
		id: "23",
		title: "おすすめWebツール７選",
		content: "業務効率化や学習に役立つWebツールを紹介します。",
		description: "業務効率化や学習に役立つWebツールを紹介します。",
		author: "著者21",
		link: "/blogs/23/",
		thumbnail: undefined,
		published_at: "2026-02-21T10:00:00.000Z",
		tags: ["Webツール", "Tips"],
	},
	{
		id: "24",
		title: "自己分析ワークシート",
		content: "自己分析を深めるための質問例とワークシートを公開します。",
		description: "自己分析を深めるための質問例とワークシートを公開します。",
		author: "著者22",
		link: "/blogs/24/",
		thumbnail: undefined,
		published_at: "2026-02-22T16:00:00.000Z",
		tags: ["自己分析", "就職活動"],
	},
	{
		id: "25",
		title: "やってはいけないJavaScriptコード10選",
		content: "バグやパフォーマンス低下を招く良くあるNGコード例を解説します。",
		description: "バグやパフォーマンス低下を招く良くあるNGコード例を解説します。",
		author: "著者23",
		link: "/blogs/25/",
		thumbnail: undefined,
		published_at: "2026-02-23T13:00:00.000Z",
		tags: ["JavaScript", "反面教師"],
	},
];
